src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    /**
     * @var Collection<int, Video>
     */
    #[ORM\OneToMany(targetEntity: Video::class, mappedBy: 'category')]
    private Collection $videos;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'category')]
    private Collection $articles;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    public function __construct()
    {
        $this->videos = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    // utilisée pour easyadmin crud
    public function __toString()
    {
        return $this->name;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): static
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setCategory($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): static
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getCategory() === $this) {
                $video->setCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setCategory($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getCategory() === $this) {
                $article->setCategory(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $subtitle = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $trailer = null;

    #[ORM\Column(length: 255)]
    private ?string $link = null;

    #[ORM\Column(length: 255)]
    private ?string $length = null;


    #[ORM\ManyToOne(inversedBy: 'videos')]
    private ?Category $category = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'video', orphanRemoval: true, cascade: ['persist'])]
    private Collection $user;

    // #[ORM\Column(type: Types::TIME_MUTABLE)]
    // private ?\DateTimeInterface $length = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $uploadedDate = null;

    #[ORM\ManyToOne(inversedBy: 'videos')]
    private ?Language $language = null;

    #[ORM\Column(length: 255)]
    private ?string $price = null;

    #[ORM\Column]
    private ?float $tva = null;

    #[ORM\Column]
    private ?bool $isHomepage = null;

    #[ORM\ManyToOne(inversedBy: 'Year')]
    private ?Season $season = null;

    // fonction pour récupéré prix TTC selon la tva choisie en BDD
    public function getPriceTvaCalculator(){
        $coeff= 1 +($this->tva/100);
        $result=$coeff*$this->price;
        $result=$result-$this->price;
        return $result;
    }

    // fonction pour récupéré le total TTC
    public function getVideoTTC(){;
        $videoTTC = 0;

        $coeff = 1+ ($this->getTva() / 100);
        // nous renvoie le total de tva
        $videoTTC += $this->getPrice()*$coeff;


        return  $videoTTC;
    }

    // utilisée pour easyadmin crud
    public function __toString()
    {
        return 
            $this->name;
            $this->season;
    }

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(string $subtitle): static
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getTrailer(): ?string
    {
        return $this->trailer;
    }

    public function setTrailer(string $trailer): static
    {
        $this->trailer = $trailer;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
            $user->setVideo($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getVideo() === $this) {
                $user->setVideo(null);
            }
        }

        return $this;
    }

    public function getLength(): ?string
    {
        return $this->length;
    }

    public function setLength(string $length): static
    {
        $this->length = $length;

        return $this;
    }

    public function getuploadedDate(): ?\DateTimeInterface
    {
        return $this->uploadedDate;
    }

    public function setuploadedDate(\DateTimeInterface $uploadedDate): static
    {
        $this->uploadedDate = $uploadedDate;

        return $this;
    }

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language): static
    {
        $this->language = $language;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function isHomepage(): ?bool
    {
        return $this->isHomepage;
    }

    public function setIsHomepage(bool $isHomepage): static
    {
        $this->isHomepage = $isHomepage;

        return $this;
    }

    public function getSeason(): ?Season
    {
        return $this->season;
    }

    public function setSeason(?Season $season): static
    {
        $this->season = $season;

        return $this;
    }

}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class CategoryController extends AbstractController
{
    #[Route('/categorie/{slug}', name: 'app_category')]
    public function index($slug, CategoryRepository $categoryRepository): Response
    {
        $category = $categoryRepository->findOneBySlug($slug);

        if(!$category){
            return $this->redirectToRoute('app_home');
        }
        
        return $this->render('category/index.html.twig', [
            'category' => $category,
        ]);
    }
}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{category.name}}{% endblock %}

{% block body %}
    <div class="album py-5">
        <div class="container">
            <h1 class="h3">{{category.name}}</h1>
            <hr>
            <p>Cette page contient {{category.videos|length}} vidéo(s) et {{category.articles|length}} article(s).</p>
            <div class="row g-3 justify-content-center">
               {% for videoElement in category.videos %}
                <div class="card col-11 col-md-3 mb-3 mx-3" style="width: 18rem;">
                    <img src="/uploads/{{videoElement.image}}" class="card-img-top" alt="...">
                    <div class="my-3 text-start">
                        <span class="badge rounded-pill text-bg-warning ms-3 px-3">Vidéo</span>
                    </div>
                    <div class="text-end">
                        <strong class="mx-2">{{videoElement.priceTvaCalculator|price}}</strong>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{videoElement.name}}</h4>
                        <hr>
                        <h5>{{videoElement.subtitle}}</h5>                           
                    </div>
                    <a href="{{ path('app_video_details', { 'slug' : videoElement.slug }) }}" class="btn btn-success">Voir la vidéo</a>
                    {# afficher le bouton uniquement pour les administrateurs #}
                    {% if app.user and "ROLE_ADMIN" in app.user.roles %}
                    <a href="{{ ea_url()
                                .setController('App\\Controller\\Admin\\VideoCrudController')
                                .setAction('edit')
                                .setEntityId(videoElement.id)
                            }}" 
                            class="btn btn-warning mt-3"><span class="me-2 fa fa-edit"></span>Editer</a>
                    {% endif %}
                </div>
                {% endfor %}
                {% for articleElement in category.articles %}
                <div class="card col-11 col-md-3 mb-3 mx-3" style="width: 18rem;">
                    <img src="/uploads/{{articleElement.image}}" class="card-img-top" alt="...">
                        <div class="my-3 text-start">
                        <span class="badge rounded-pill text-bg-info ms-3 px-3">Article</span>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{articleElement.title}}</h4>
                        <hr>
                        <h5>{{articleElement.subtitle}}</h5>                           
                    </div>
                    <a href="{{ path('app_video_details', { 'slug' : articleElement.slug }) }}" class="btn btn-success">Voir la vidéo</a>
                    {# afficher le bouton uniquement pour les administrateurs #}
                    {% if app.user and "ROLE_ADMIN" in app.user.roles %}
                    <a href="{{ ea_url()
                                .setController('App\\Controller\\Admin\\VideoCrudController')
                                .setAction('edit')
                                .setEntityId(articleElement.id)
                            }}" 
                            class="btn btn-warning mt-3"><span class="me-2 fa fa-edit"></span>Editer</a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}