src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $LastName = null;

    #[ORM\ManyToOne(inversedBy: 'user')]
    private ?Video $video = null;

    /**
     * @var Collection<int, Address>
     */
    #[ORM\OneToMany(targetEntity: Address::class, mappedBy: 'user')]
    private Collection $addresses;

    /**
     * @var Collection<int, Order>
     */
    #[ORM\OneToMany(targetEntity: Order::class, mappedBy: 'user')]
    private Collection $orders;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable:true)]
    private ?\DateTimeInterface $lastLoginAt = null;

    public function __construct()
    {
        $this->addresses = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getFirstName().' '.$this->getLastName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getVideo(): ?Video
    {
        return $this->video;
    }

    public function setVideo(?Video $video): static
    {
        $this->video = $video;

        return $this;
    }

    // test

    
    // public function addVideo(Video $video): void
    // {
    //     $video->setUser($this);

    //     if (!$this->video->contains($video)) {
    //         $this->video->add($video);
    //     }
    // }

    // public function removeVideo(Video $video): void
    // {
    //     $this->video->removeElement($video);
    // }

    /**
     * @return Collection<int, Address>
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): static
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses->add($address);
            $address->setUser($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): static
    {
        if ($this->addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    public function getLastLoginAt(): ?\DateTimeInterface
    {
        return $this->lastLoginAt;
    }

    public function setLastLoginAt(\DateTimeInterface $lastLoginAt): static
    {
        $this->lastLoginAt = $lastLoginAt;

        return $this;
    }

}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Address;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('addresses', EntityType::class, [
                'label'=>'Choisissez votre adresse de facturation',
                'required'=>true,
                'class'=>Address::class,
                'expanded'=>true,
                'choices'=>$options['addresses'],
                'label_html'=>true,
            ])
            ->add('submit', SubmitType::class,[
                'label'=>"Valider l'adresse",
                'attr'=>[
                    'class'=>'btn btn-success w-100'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'addresses'=>null
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\OrderDetail;
use App\Form\OrderType;
use App\Repository\EventRepository;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Attribute\Route;

final class OrderController extends AbstractController
{
    public function __construct(
        private readonly VideoRepository $videoRepository,
        private readonly EventRepository $eventRepository,
    ) {
    }

    #[Route('/commande/adresse', name: 'app_order')]
    public function index(): Response
    {
        $addresses = $this->getUser()->getAddresses();

        if(count($addresses)==0){
            return $this->redirectToRoute('app_user_account_address_form');
        }


        $form=$this->createForm(OrderType::class, null, [
            'addresses'=>$addresses,
            'action'=>$this->generateUrl('app_recap'),
        ]);

        return $this->render('order/index.html.twig', [
            'facturationForm' => $form->createView(),
        ]);
    }

    #[Route('/commande/recapitulatif', name: 'app_recap')]
    public function recapAndAddInDataBase(Request $request, SessionInterface $session, EntityManagerInterface $entityManager): Response
    {
        if($request->getMethod()!= 'POST'){
            return $this->redirectToRoute('app_panier');
        }

        $panier = $session->get('panier',[]);
        $data=[];

        $totalVideoHT=0;
        $totalVideoTTC=0;
        $totalVideoTVA=0;

        $totalHT=0;
        $totalTTC=0;
        $totalTVA=0;

        foreach($panier as $key => $quantity){
            $video = $this->videoRepository->find($key);
            $data[]= [
                "video"=>$video,
                "quantity"=>$quantity,
            ];
            $totalVideoHT += $video->getPrice() * $quantity;
            $totalVideoTTC += $video->getVideoTTC()*$quantity;
            $totalVideoTVA += $video->getPriceTvaCalculator()*$quantity;
        }

        // ----------- TICKETS ---------
        $panierReservationNoFood = $session->get('panierReservationNoFood', []);
        $panierReservationWithFood = $session->get('panierReservationWithFood', []);

        $dataEventNoFood=[];
        $dataEventWithFood=[];

        $totalPriceEventWithFood=0;
        $totalPriceEventNoFood=0;
        $totalPriceReservations=0;

        $totalNumberOfEventWithFood=0;
        $totalNumberOfEventNoFood=0;
        $totalNumberOfReservations=0;

        foreach($panierReservationNoFood as $key => $quantity){

            $quantityNoFood=$panierReservationNoFood[$key];

            $eventReservationNoFood=$this->eventRepository->find($key);

            // dd($eventReservationNoFood);

            $dataEventNoFood[]= [
                "panierReservationNoFood"=>$eventReservationNoFood,
                "quantity"=>$quantityNoFood,
            ];
         
            $eventReservationNoFood->getEventPriceNoFood()*$quantityNoFood;
            $totalNumberOfEventNoFood= $quantityNoFood;

            $totalPriceEventNoFood += $eventReservationNoFood->getEventPriceNoFood()*$quantityNoFood;
            $totalNumberOfEventNoFood= $quantityNoFood;

            $totalPriceReservations+=$totalPriceEventNoFood;
            $totalNumberOfReservations+=$totalNumberOfEventNoFood;
        }

        foreach($panierReservationWithFood as $key => $quantity){

            $quantityWithFood=$panierReservationWithFood[$key];

            $eventReservationWithFood=$this->eventRepository->find($key);

            $dataEventWithFood[]= [
                "panierReservationWithFood"=>$eventReservationWithFood,
                "quantity"=>$quantityWithFood,
            ];
         
            $eventReservationWithFood->getEventPriceWithFood()*$quantityWithFood;
            $totalNumberOfEventWithFood= $quantityWithFood;

            $totalPriceEventWithFood += $eventReservationWithFood->getEventPriceWithFood()*$quantityWithFood;
            $totalNumberOfEventWithFood= $quantityWithFood;

            $totalPriceReservations+=$totalPriceEventWithFood;
            $totalNumberOfReservations+=$totalNumberOfEventWithFood;
        }

        // ---------- FIN TICKETS --------

        // ------------ CALCULS TOTAUX $ ----------
        $totalEventsHT = $totalPriceReservations/1.2;
        $totalEventsTTC= $totalPriceReservations;
        $totalEventsTVA = $totalPriceReservations*0.2;
        
        $totalHT=$totalVideoHT+$totalEventsHT;
        $totalTTC=$totalVideoTTC+$totalEventsTTC;
        $totalTVA=$totalVideoTVA+$totalEventsTVA;

        $form=$this->createForm(OrderType::class, null, [
            'addresses'=>$this->getUser()->getAddresses(),
        ]);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            // création chaine de caractère Adresse
            $addressObject=$form->get('addresses')->getData();

            $address= $addressObject->getEnterprise().'<br>';
            $address .= $addressObject->getFirstName().' '.$addressObject->getLastName().'<br>';
            $address.= $addressObject->getPhone().'<br>';
            $address.= $addressObject->getAddress().'<br>';
            $address.= $addressObject->getCity().' '.$addressObject->getPostCode().'<br>';
            $address.= $addressObject->getCountry();

            $order = new Order;
            $order->setUser($this->getUser());
            $order->setCreatedAt(new \DateTime());
            $order->setStatus(1);
            $order->setAddressFacturation($address);

            foreach($data as $product){
                // dd($product['quantity']);
                $orderDetail= New OrderDetail();
                $orderDetail->setProductName($product['video']->getName());
                $orderDetail->setProductImage($product['video']->getImage());
                $orderDetail->setProductQuantity($product['quantity']);
                $orderDetail->setProductPrice($product['video']->getPrice());
                $orderDetail->setProductTVA($product['video']->getTva());
                // dd($product['video']->getTva());

                // on récupère le contenu du panier et on le greffe à orderDetail
                $order->addOrderDetail($orderDetail);
            }
            foreach($dataEventNoFood as $eventNoFood){
                $orderDetail= New OrderDetail();
                $orderDetail->setProductName($eventNoFood['panierReservationNoFood']->getName().' | Formule Pass\'Evènement Seul');
                $orderDetail->setProductImage($eventNoFood['panierReservationNoFood']->getImage());
                // dd($eventNoFood['panierReservationNoFood']->getImage());
                $orderDetail->setProductQuantity($eventNoFood['quantity']);
                $orderDetail->setProductPrice($eventNoFood['panierReservationNoFood']->getEventPriceNoFoodHT());
                // dd($eventNoFood['panierReservationNoFood']->getEventPriceNoFoodHT());
                $orderDetail->setProductTVA(20.0);
                $orderDetail->setPlace($eventNoFood['panierReservationNoFood']->getPlace());
                $orderDetail->setdateEvent($eventNoFood['panierReservationNoFood']->getEventDate());
                // on récupère le contenu du panier et on le greffe à orderDetail
                $order->addOrderDetail($orderDetail);
            }
            foreach($dataEventWithFood as $eventWithFood){
                // dd($dataEventWithFood);
                $orderDetail= New OrderDetail();
                $orderDetail->setProductName($eventWithFood['panierReservationWithFood']->getName().' | Formule Pass\'Evènement + Repas');
                $orderDetail->setProductImage($eventWithFood['panierReservationWithFood']->getImage());
                $orderDetail->setProductQuantity($eventWithFood['quantity']);
                $orderDetail->setProductPrice($eventWithFood['panierReservationWithFood']->getEventPriceWithFoodHT());
                $orderDetail->setProductTVA(20.0);
                $orderDetail->setPlace($eventWithFood['panierReservationWithFood']->getPlace());
                $orderDetail->setdateEvent($eventWithFood['panierReservationWithFood']->getEventDate());

                // on récupère le contenu du panier et on le greffe à orderDetail
                $order->addOrderDetail($orderDetail);
            }
            
            // on envoie en BDD
            $entityManager->persist($order);
            $entityManager->flush();

        }

        return $this->render('order/recap.html.twig', [
            'address' => $form->getData(),
            'data' => $data,
            'dataEventNoFood'=>$dataEventNoFood,
            'dataEventWithFood'=>$dataEventWithFood,
            'totalHT' => $totalHT,
            'totalTTC' => $totalTTC,
            'totalTVA' => $totalTVA,
            'order'=>$order,
            'totalPriceEventNoFood' => $totalPriceEventNoFood,
            'totalPriceEventWithFood'=>$totalPriceEventWithFood,
            'totalPriceReservations'=>$totalPriceReservations,
            'totalNumberOfEventNoFood'=>$totalNumberOfEventNoFood,
            'totalNumberOfEventWithFood'=>$totalNumberOfEventWithFood,
            'totalNumberOfReservations'=>$totalNumberOfReservations,
        ]);
    }
}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ma Commande{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="d-flex justify-content-end">
            <a href="{{path('app_panier')}}" class="btn btn-warning">Revenir à l'étape précédente</a>
    </div>
    <h1>Ma commande</h1>
    <hr class="mb-5">
    <div class="row justify-content-between">
        <!-- Shopping Cart Items -->
        <div class="col-10 col-md-9">
            <h2 class="h4 mb-3">Choix de l'adresse de facturation</h2>  
            <div>
                {{form(facturationForm)}}
            </div>
        </div>
        <div class="col-md-3">
                <a href="{{path('app_user_account_address_form')}}" class="btn btn-primary">Ajouter une adresse de facturation</a>
        </div>
    </div>
</div>
{% endblock %}

templates/order/recap.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulatif{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="row">
        <!-- Shopping Cart Items -->
        <div class="d-flex justify-content-end">
                <a href="{{path('app_order')}}" class="btn btn-warning">Revenir à l'étape précédente</a>
        </div>
        <div class="col-10 col-md-7">
            <h1>Récapitulatif de la commande</h1>
            <hr class="mb-5">
            <div class="row">
                <h3 class="h4 mb-5">Article(s) de la commande :</h3>
                {% for item in data %}
                <div class="cart-item d-flex justify-content-between bg-color-cart p-3 rounded mb-4">
                    <div class="d-flex">
                        <img src="/uploads/{{item.video.image}}" alt="Product" class="product-img me-3">
                        <div>
                            <h3 class="h5">{{item.video.name}}</h3>
                            <p class="text-muted">{{item.video.subtitle}}</p>
                            <span class="badge badge-pill badge-primary fs-6 p-2">Vidéo à la demande</span>
                        </div>
                    </div>
                    <div class="d-flex flex-column justify-content-between col-1">
                        <span>{{item.video.videoTTC|price}}</span>
                        {# on transmet à la route l'id de l'item en question #}
                        {# <a href="{{path('app_delete_panier', {id:item.video.id})}}" class="btn btn-sm btn-danger">Supprimer</a> #}
                    </div>
                </div>
                {% endfor %}
                {# tickets #}
                {% for item in dataEventNoFood %}
                <div class="cart-item d-flex justify-content-between bg-color-cart p-3 rounded mb-4">
                    <div class="d-flex">
                        <img src="/uploads/{{item.panierReservationNoFood.image}}" alt="Product" class="product-img me-3">
                        <div>
                            <h3 class="h5">{{item.panierReservationNoFood.name}}</h3>
                            <p class="text-muted">{{item.panierReservationNoFood.subtitle}}</p>
                            <p class="badge badge-pill badge-primary fs-6 p-2">Formule Pass'Evènement Seul | {{item.quantity}} tickets</p>
                        </div>
                    </div>
                    <div class="d-flex flex-column justify-content-between  col-1">
                        <span>{{totalPriceEventNoFood|price}}</span>
                        {# <a href="{{path('app_event_reservation', {id:item.panierReservationNoFood.id})}}" class="btn btn-sm btn-danger">Modifier la formule</a> #}
                    </div>
                </div>
                {% endfor %}
                {% for item in dataEventWithFood %}
                <div class="cart-item d-flex justify-content-between bg-color-cart p-3 rounded mb-4">
                    <div class="d-flex">
                        <img src="/uploads/{{item.panierReservationWithFood.image}}" alt="Product" class="product-img me-3">
                        <div>
                            <h3 class="h5">{{item.panierReservationWithFood.name}}</h3>
                            <p class="text-muted">{{item.panierReservationWithFood.subtitle}}</p>
                            <p class="badge badge-pill badge-primary fs-6 p-2">Formule Pass'Evènement + Repas | {{item.quantity}} tickets</p>
                        </div>
                    </div>
                    <div class="d-flex flex-column justify-content-between  col-1">
                        <span>{{totalPriceEventWithFood|price}}</span>
                        {# <a href="{{path('app_event_reservation', {id:item.panierReservationWithFood.id})}}" class="btn btn-sm btn-danger">Modifier la formule</a> #}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row mt-3">
                <h3 class="h4">Adresse de facturation choisie :</h3>
                <div class="p-2 m-3 bg-color-cart text-center">
                    <strong>{{address.addresses.enterprise}}</strong><br>
                    <strong>{{address.addresses.firstName}} {{address.addresses.lastName}}</strong><br>
                    {{address.addresses.phone}}<br>
                    {{address.addresses.address}}<br>
                    {{address.addresses.postCode}}, {{address.addresses.city}}<br>
                    {{address.addresses.country}}<br>
                </div>
            </div>
        </div>
        <!-- Cart Summary -->
        <div id="recap-cart" class="col-10 col-md-4 offset-md-1 bg-color-cart p-3 rounded my-5">
            <div class="cart-summary">
                <h2 class="h4 mb-4 text-center mb-5">Récapitulatif de la commande</h2>
                <ul class="list-unstyled">
                    <li class="d-flex justify-content-between  my-2">
                        <span class="total-price">Total HT :</span>
                        <span class="total-price">{{totalHT|price}}</span>
                    </li>
                    <hr class="my-4">
                    <li class="d-flex justify-content-between  my-2">
                        <span class="total-price">Total TVA :</span>
                        <span class="total-price">{{totalTVA|price}}</span>
                    </li>
                    <hr class="my-4">
                    <li class="d-flex justify-content-between  my-2">
                        <strong class="total-price">Total TTC :</strong>
                        <strong class="total-price">{{totalTTC|price}}</strong>
                    </li>
                </ul>
                {# <a href="{{path('app_payment')}}" class="btn btn-success w-100 mt-3">Valider le panier</a> #}
                <a href="{{path('app_payment', {'id_order': order.id})}}" class="btn btn-success w-100 mt-3">Payer la commande</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}